#!/bin/bash

# Configuration
LOG_FILE="/var/log/sftp.log"
# 1.7 GB in Kilobytes (1.7 * 1024 * 1024)
MAX_SIZE=1782579
currDate=`date "+%Y%m%d"`
debugFile=/root/sftplog/debug.txt
fail_sftp=/root/sftplog/sftp_Fail_${currDate}.txt
success_sftp=/root/sftplog/sftp_Success_${currDate}.txt

# Get current file size in Kilobytes
CURRENT_SIZE=$(du -k "$LOG_FILE" | cut -f1) >>  /root/sftplog/sftp.log_${currDate}

if [ "$CURRENT_SIZE" -gt "$MAX_SIZE" ]; then
    echo "Log file ($CURRENT_SIZE KB) exceeds 1.7 GB. Trimming..." >> /root/sftplog/sftp.log_${currDate}

   # Method 1: Keep the last 10,000 lines (safest for logs)
   # tail -n 10000 "$LOG_FILE" > "$LOG_FILE.tmp" && mv "$LOG_FILE.tmp" "$LOG_FILE"

   # Method 2: move the file (fastest)
    #  mv $LOG_FILE ${LOG_FILE}_$currDate

   #create file new sftp file
    # touch $LOG_FILE

   #set permission
    # chmod 0644 $LOG_FILE

    #restart rsyslog
   #  systemctl restart rsyslog.service
: << 'COMMENT'
        if [ $? -eq 0 ];then
         ps -ef | grep filepattern.pl| grep -v grep | awk '{print $2}' | xargs kill -9
                   if [ $? -ne 0 ]
                   then
                        echo "Unable to killed filepattern.pl"  >> $fail_sftp
                        else
                        echo "filepattern.pl is killed " >> $success_sftp
                   fi
                   ps -ef | grep filepattern.pl | grep -v grep
                   if [ $? -eq 0 ]; then
                   echo "filepattern.pl is already running"    >> $fail_sftp
                   else
                        cd /vpsuser/vps_utility_code
                        su - vpsuser -c nohup ./filepattern.pl &
                        if [ $? -ne 0 ]
                        then
                        echo "Unable to start filepattern.pl "  >> $fail_sftp
                        else
                        echo "filepattern.pl  is started " >> $success_sftp
                        fi
                  fi

        fi
COMMENT
    echo "Filepattern also restarted & Trimming complete." >> /root/sftplog/sftp.log_${currDate}
else
    echo "Log size is safe ($CURRENT_SIZE KB)."
fi

